# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DFIRScience # jekyll-seo-tag > Owners twitter username
author: DFIRScience # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name:  # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Linking Organized Crime and Cybercrime 2018" # The post list page content
    feature_text:
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Alembic" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Linking Organized Crime and Cybercrime, June 26-27, 2018 in Chuncheon, South Korea" # Site description and default description, also used in jekyll-seo-tag
url: "https://LOCC.DFIR.Science" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: ""
email: "joshua+LOCC@dfirscience.org"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Submit: /submit/
  About LOCC: /about/
  News: /news/
  Venue and Info: /venue/

navigation_footer:
  **Linking Organized Crime and Cybercrime 2018** conference site. Sponsored by
  [UNODC](https://www.unodc.org/) and hosted by [LIFS@Hallym](https://cis.hallym.ac.kr).

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
